create schema if not exists auth;
create table if not exists auth.users(id uuid primary key,email text);
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid; $$;
grant usage on schema auth,public to authenticated,service_role;
grant execute on function auth.uid() to authenticated,service_role;
alter default privileges in schema public grant all on tables to service_role;
create extension if not exists vector;
create table if not exists public."RAGformyAIagent" (id bigint, content text, metadata jsonb, embedding public.vector(3));
create schema if not exists storage;
create table if not exists storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table if not exists storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
alter table storage.objects enable row level security;
grant usage on schema storage to authenticated;
grant select,insert,delete on storage.objects to authenticated;
create or replace function storage.foldername(name text) returns text[] language sql immutable as $$ select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]; $$;
